"""
Due the following class and we will talk the solution at the beginning of the following class.
Please ONLY submit it to black board. 

1. Write a function to get the sum of 1 to n(inclusively). Define sum of 1 to m as s(m). Save results of s(m) into a list named s. m from 0 to n. return s(n) which is the sum of 1 to n. (hint: You can initialize the s=[0]*(n+1). Then s[0]=0, s[1]=s[0]+1, s[2]=s[1]+2 ... s[n]=s[n-1]+n)
"""

def sum_1_to_n(n):
    n = 6
    a = [i for i in range(1, n+1)]
    print(a)
    s = [0]*(n+1)
    for i in range(1, n+1):
        # s[0] = 0
        # s[1] = sum([1]) = 0 + 1 = s[0] + 1 =1
        # s[2] = sum([1, 2]) = 1 + 2 = s[1] + 2
        # s[3] = sum([1, 2, 3]) = (1+2)+3 = s[2]+3
        s[i] = s[i-1] + i
    print(s)
    return s[-1]
    # return s[n]

sum_1_to_n(6)

"""
2. given a list 
a=[-1, 2, 3,-4, -8, 9, -100, -100, 90]
get the index of minimum value of this list.
get the index of maximum value of this list.

3. plot y=2*x,  x is from 0 to 10 with step of 0.1. (hint: you can write xs=[0+0.1*i for i in range(int(10/0.1))])
4. plot y=n*(n+1)//2  n is from 0 to 100 with step of 1. 
5. plot y=e**x. x is from 0 to 10 with step of 0.1. (hint: e can be get by import math; math.e)
6. The following list :
                   [[0, 0],[0, 1], [0, 2],
                    [1, 0],[1, 1], [1, 2]]
    can be easiler generated by using:
a=[[i,j] for i in range(2)
         for j in range(3)]
Try to run the following code to see what kind of list will be generated.
a=[[i,j] for i in range(5)
         for j in range(10)]

"""
